FROM python:3.9-slim

# Set environment variables for Chrome binary and driver
ENV CHROME_BIN=/usr/bin/google-chrome-stable
ENV SAUCE_USERNAME=oauth-kasanwidjojojeiel-30890
ENV SAUCE_ACCESS_KEY=da6c39f1-bc81-4e03-ba16-b617ff0cc79f

# Install dependencies and Google Chrome
RUN apt-get update && apt-get install -y wget curl unzip \
    && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    && apt install -y ./google-chrome-stable_current_amd64.deb

# Install Chromedriver
RUN CHROME_DRIVER_VERSION=$(curl -sSL https://chromedriver.storage.googleapis.com/LATEST_RELEASE) \
    && wget https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip \
    && unzip chromedriver_linux64.zip -d /usr/local/bin/ \
    && rm chromedriver_linux64.zip

# Install Python dependencies
COPY requirements.txt . 
RUN pip install -r requirements.txt

# Set working directory
WORKDIR /app
COPY . .

CMD ["python", "main.py"]
